//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitAMerica.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionDetail
    {
        public int VersionDetailsId { get; set; }
        public Nullable<int> VersionTypeId { get; set; }
        public string Version { get; set; }
        public string FileName { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual VersionType VersionType { get; set; }
    }
}
